M48
; DRILL file {KiCad 8.0.4} date 2024-08-24T14:43:58+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-24T14:43:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X33.57Y8.89
X33.57Y3.11
T2
X2.0Y69.2
X21.9Y37.6
X26.7Y71.7
X37.6Y17.7
M30
